name: CI

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    ci-step:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16, 18]
                target: ['ci:build', 'ci:test', 'ci:lint']

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies
              run: npm i
              shell: bash

            - name: Run ${{ matrix.target }}
              run: npm run ${{ matrix.target }}
              shell: bash

    commitlint:
        runs-on: ubuntu-latest
        if: github.event_name == 'pull_request'
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Install dependencies
              run: npm i
              shell: bash

            - name: Validate PR commits with commitlint
              run: npx commitlint --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} --to ${{ github.event.pull_request.head.sha }} --verbose

    sonarcloud:
        name: SonarCloud
        runs-on: ubuntu-latest
        needs: [ci-step, commitlint] # Ensure the repository pass validation before running SonarCloud
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
            - name: Install dependencies
              run: npm i
              shell: bash
            - name: Test and coverage
              run: npm run ci:test:coverage
              shell: bash
            - name: SonarCloud Scan
              uses: SonarSource/sonarcloud-github-action@master
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
